-- SuperHash v2.0: Verified autonomous hash design via E-graphs + LLM discovery
import SuperHash.CryptoOp
import SuperHash.DesignParams
import SuperHash.Pareto
import SuperHash.Instances
import SuperHash.CryptoNodeOps
import SuperHash.EGraph.UnionFind
import SuperHash.EGraph.Core
import SuperHash.EGraph.CoreSpec
import SuperHash.EGraph.EMatch
import SuperHash.EGraph.Consistency
import SuperHash.EGraph.AddNodeTriple
import SuperHash.EGraph.Tests
import SuperHash.Rules.SoundRule
import SuperHash.Rules.CryptoRules
import SuperHash.Rules.NonVacuity
import SuperHash.Rules.BlockBridge
import SuperHash.Pipeline.Saturate
import SuperHash.Pipeline.EMatchSpec
import SuperHash.Pipeline.Extract
import SuperHash.Pipeline.Instances
import SuperHash.Pipeline.Soundness
import SuperHash.Pareto.Scalarization
import SuperHash.Pareto.Extract
import SuperHash.Pareto.Soundness
import SuperHash.Pipeline.Integration
import SuperHash.Pipeline.MasterTheorem
import SuperHash.Instances.Evaluation
import SuperHash.Instances.BlockDesigns
import SuperHash.Discovery.RuleCandidate
import SuperHash.Discovery.RuleVerifier
import SuperHash.Discovery.RulePool
import SuperHash.Concrete.BitVecOps
import SuperHash.Concrete.Bridge
import SuperHash.SmoothE.CostModel
import SuperHash.SmoothE.Extract
import SuperHash.DesignLoop.Core
import SuperHash.DesignLoop.Soundness
import SuperHash.Pipeline.MasterTheoremV2
-- v2.5: Real crypto semantics
import SuperHash.Crypto.Semantics
import SuperHash.Crypto.CryptoEval
import SuperHash.Crypto.CryptoRule
import SuperHash.Crypto.DDT
import SuperHash.Crypto.AlgebraicDegree
import SuperHash.Crypto.Fitness
import SuperHash.Crypto.SourceEntropy
import SuperHash.Crypto.ExtractorBound
import SuperHash.Crypto.UHFConstraint
import SuperHash.Crypto.ZKSideInfo
import SuperHash.Crypto.AESSbox
import SuperHash.Crypto.CryptoNodeSemantics
import SuperHash.Crypto.BouraCanteutBound
import SuperHash.Crypto.SecurityNotions
import SuperHash.Crypto.HigherOrderDiff
import SuperHash.Crypto.LinearLayerDegree
import SuperHash.Pipeline.CompletenessSpec
import SuperHash.Bridge.TrustHashFitness
import SuperHash.TrustHash.NiceTree
import SuperHash.TrustHash.Verdict
import SuperHash.Rules.CryptoRulesCS
import SuperHash.Rules.ExpansionRules
import SuperHash.Crypto.ExpanderBounds
