#!/usr/bin/env python3
"""
SuperHash v4.0 — AXLE Integration Layer (Lean verification)

Verifies LLM-proposed rewrite rules by:
  1. Generating a standalone .lean file with the rule + proof attempt
  2. Compiling via `lake env lean <file>` (the Lean kernel IS the verifier)
  3. Parsing stdout/stderr for success/failure/timeout

Three-Tier Bridge (D7):
  Tier 1 (Python): This script — IO shell, generates Lean, invokes compiler
  Tier 2 (Lean): Kernel verification of generated proof
  Tier 3: Binary result (SOUND/UNSOUND/TIMEOUT/PARSE_ERROR)

Usage:
  python3 scripts/axle_integration.py --candidate rule.json
  python3 scripts/axle_integration.py --candidate rule.json --timeout 120
  python3 scripts/axle_integration.py --batch rules/
  python3 scripts/axle_integration.py --test
"""

from __future__ import annotations

import json
import subprocess
import sys
import time
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).parent))

from config import LEAN_PROJECT_DIR, VERIFICATION_TIMEOUT, GEN_DIR


class VerificationResult(Enum):
    SOUND = "sound"
    UNSOUND = "unsound"
    TIMEOUT = "timeout"
    PARSE_ERROR = "parse_error"


@dataclass
class RuleCandidate:
    name: str
    classification: str  # "equivalence" | "improvement" | "conditional"
    lhs_template: str    # Canonical CryptoExpr string
    rhs_template: str    # Canonical CryptoExpr string
    side_condition: Optional[str] = None
    source: str = "unknown"
    confidence: int = 50

    @classmethod
    def from_json(cls, data: dict) -> "RuleCandidate":
        return cls(
            name=data["name"],
            classification=data["classification"],
            lhs_template=data["lhs_template"],
            rhs_template=data["rhs_template"],
            side_condition=data.get("side_condition"),
            source=data.get("source", "unknown"),
            confidence=data.get("confidence", 50),
        )

    def to_json(self) -> dict:
        d = {
            "name": self.name,
            "classification": self.classification,
            "lhs_template": self.lhs_template,
            "rhs_template": self.rhs_template,
            "source": self.source,
            "confidence": self.confidence,
        }
        if self.side_condition:
            d["side_condition"] = self.side_condition
        return d


@dataclass
class VerificationReport:
    candidate: RuleCandidate
    result: VerificationResult
    elapsed_ms: int = 0
    error_message: Optional[str] = None
    repaired: bool = False

    def to_json(self) -> dict:
        return {
            "name": self.candidate.name,
            "result": self.result.value,
            "elapsed_ms": self.elapsed_ms,
            "error_message": self.error_message,
            "repaired": self.repaired,
        }


# ============================================================
# Lean source generation
# ============================================================

def _sanitize_name(name: str) -> str:
    """Sanitize a rule name for use as a Lean identifier."""
    # Replace non-alphanumeric chars with underscore
    sanitized = ""
    for ch in name:
        if ch.isalnum() or ch == "_":
            sanitized += ch
        else:
            sanitized += "_"
    # Ensure starts with lowercase letter
    if sanitized and not sanitized[0].isalpha():
        sanitized = "r_" + sanitized
    return sanitized


def generate_lean_source(rc: RuleCandidate) -> str:
    """Generate a Lean 4 file that verifies the rule candidate.

    The file imports the project's Discovery module, constructs a
    RuleCandidate, and attempts a proof of semantic equivalence using
    a cascade of tactics:
      1. simp with CryptoExpr.eval + arithmetic lemmas
      2. ring (for polynomial identities)
      3. omega (for linear arithmetic)

    If the proof fails, the file won't compile -- binary verification.
    """
    safe_name = _sanitize_name(rc.name)

    # Build tactic cascade: try multiple strategies
    tactic_block = """\
    intro env
    simp [CryptoExpr.eval, Nat.add_assoc, Nat.mul_assoc, Nat.mul_comm,
          Nat.add_comm, Nat.mul_add, Nat.add_mul, Nat.mul_left_comm]
    <;> omega"""

    return f"""\
-- Auto-generated by axle_integration.py for rule: {rc.name}
-- Classification: {rc.classification} | Source: {rc.source}
import SuperHash.Discovery.RuleVerifier

namespace SuperHash

set_option maxHeartbeats 400000 in
/-- Auto-verified rule: {rc.name} -/
def verified_{safe_name} : VerifiedRule :=
  verifyCandidate
    {{ name := "{rc.name}"
       classification := .{rc.classification}
       lhsTemplate := {rc.lhs_template}
       rhsTemplate := {rc.rhs_template}
       source := "{rc.source}"
       confidence := {rc.confidence} }}
    (by
{tactic_block})

-- Non-vacuity smoke test
#eval verified_{safe_name}.candidate.quickCheck (fun _ => 1)
#eval verified_{safe_name}.candidate.quickCheck (fun x => x + 1)

end SuperHash
"""


# ============================================================
# Verification via lake env lean
# ============================================================

def verify_rule(
    rc: RuleCandidate,
    project_path: Optional[Path] = None,
    timeout_seconds: Optional[int] = None,
) -> VerificationReport:
    """Verify a rule candidate by compiling a generated Lean file.

    Steps:
      1. Generate a .lean file in _gen/ directory
      2. Run `lake env lean <file>` to compile
      3. Parse exit code: 0 = SOUND, nonzero = UNSOUND/TIMEOUT/PARSE_ERROR
      4. Clean up generated file

    Returns VerificationReport with result and timing.
    """
    if project_path is None:
        project_path = LEAN_PROJECT_DIR
    if timeout_seconds is None:
        timeout_seconds = VERIFICATION_TIMEOUT

    start = time.time()

    # Ensure _gen directory exists
    gen_dir = project_path / "SuperHash" / "Discovery" / "_gen"
    gen_dir.mkdir(parents=True, exist_ok=True)

    safe_name = _sanitize_name(rc.name)
    gen_file = gen_dir / f"verify_{safe_name}.lean"

    try:
        # Generate Lean source
        source = generate_lean_source(rc)
        gen_file.write_text(source)

        # Compile with lake env lean
        result = subprocess.run(
            ["lake", "env", "lean", str(gen_file)],
            cwd=str(project_path),
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
        )

        elapsed = int((time.time() - start) * 1000)

        if result.returncode == 0:
            return VerificationReport(rc, VerificationResult.SOUND, elapsed)
        else:
            # Classify the failure
            stderr = result.stderr
            stdout = result.stdout

            # Check for sorry (incomplete proof)
            if "sorry" in stderr.lower() or "sorry" in stdout.lower():
                return VerificationReport(
                    rc, VerificationResult.UNSOUND, elapsed,
                    error_message="Proof contains sorry"
                )

            # Check for type mismatch / tactic failure
            if "type mismatch" in stderr or "tactic" in stderr.lower():
                # Extract first meaningful error line
                error_lines = [
                    line for line in stderr.split("\n")
                    if "error" in line.lower() or "tactic" in line.lower()
                ]
                error_msg = error_lines[0][:300] if error_lines else stderr[:300]
                return VerificationReport(
                    rc, VerificationResult.UNSOUND, elapsed,
                    error_message=error_msg,
                )

            # Check for heartbeat timeout
            if "heartbeats" in stderr.lower():
                return VerificationReport(
                    rc, VerificationResult.TIMEOUT, elapsed,
                    error_message="Exceeded heartbeat limit",
                )

            # Generic failure
            return VerificationReport(
                rc, VerificationResult.UNSOUND, elapsed,
                error_message=stderr[:500] if stderr else stdout[:500],
            )

    except subprocess.TimeoutExpired:
        elapsed = int((time.time() - start) * 1000)
        return VerificationReport(
            rc, VerificationResult.TIMEOUT, elapsed,
            error_message=f"Process killed after {timeout_seconds}s",
        )
    except FileNotFoundError:
        elapsed = int((time.time() - start) * 1000)
        return VerificationReport(
            rc, VerificationResult.PARSE_ERROR, elapsed,
            error_message="'lake' command not found — is Lean/Lake installed?",
        )
    except Exception as e:
        elapsed = int((time.time() - start) * 1000)
        return VerificationReport(
            rc, VerificationResult.PARSE_ERROR, elapsed,
            error_message=str(e)[:500],
        )
    finally:
        # Clean up generated file
        if gen_file.exists():
            gen_file.unlink()
        # Clean up _gen dir if empty
        try:
            if gen_dir.exists() and not any(gen_dir.iterdir()):
                gen_dir.rmdir()
        except OSError:
            pass


def verify_batch(
    candidates: list[RuleCandidate],
    project_path: Optional[Path] = None,
    timeout_seconds: Optional[int] = None,
) -> list[VerificationReport]:
    """Verify a batch of rule candidates sequentially.

    Returns a list of VerificationReports in the same order.
    """
    reports = []
    for i, rc in enumerate(candidates):
        print(f"  Verifying [{i+1}/{len(candidates)}] {rc.name}...", end=" ", flush=True)
        report = verify_rule(rc, project_path, timeout_seconds)
        symbol = {
            VerificationResult.SOUND: "SOUND",
            VerificationResult.UNSOUND: "UNSOUND",
            VerificationResult.TIMEOUT: "TIMEOUT",
            VerificationResult.PARSE_ERROR: "PARSE_ERROR",
        }[report.result]
        print(f"{symbol} ({report.elapsed_ms}ms)")
        reports.append(report)
    return reports


# ============================================================
# Round-trip TCB validation (D11)
# ============================================================

def round_trip_check(rc: RuleCandidate) -> bool:
    """Verify round-trip: JSON -> RuleCandidate -> JSON -> RuleCandidate.
    Returns True if both serializations match.
    """
    j1 = rc.to_json()
    rc2 = RuleCandidate.from_json(j1)
    j2 = rc2.to_json()
    return j1 == j2


# ============================================================
# CLI
# ============================================================

def main() -> None:
    if "--help" in sys.argv or len(sys.argv) < 2:
        print(__doc__)
        sys.exit(0)

    project_path = LEAN_PROJECT_DIR

    timeout_seconds = VERIFICATION_TIMEOUT
    if "--timeout" in sys.argv:
        idx = sys.argv.index("--timeout") + 1
        timeout_seconds = int(sys.argv[idx])

    if "--candidate" in sys.argv:
        idx = sys.argv.index("--candidate") + 1
        candidate_file = Path(sys.argv[idx])
        with open(candidate_file) as f:
            data = json.load(f)
        rc = RuleCandidate.from_json(data)

        # Round-trip check
        if not round_trip_check(rc):
            print(f"FAIL: Round-trip check failed for {rc.name}")
            sys.exit(1)

        report = verify_rule(rc, project_path, timeout_seconds)
        print(json.dumps(report.to_json(), indent=2))

    elif "--batch" in sys.argv:
        idx = sys.argv.index("--batch") + 1
        batch_dir = Path(sys.argv[idx])
        candidates = []
        for f in sorted(batch_dir.glob("*.json")):
            with open(f) as fh:
                data = json.load(fh)
            candidates.append(RuleCandidate.from_json(data))

        if not candidates:
            print(f"No .json files found in {batch_dir}")
            sys.exit(1)

        reports = verify_batch(candidates, project_path, timeout_seconds)
        for report in reports:
            print(json.dumps(report.to_json(), indent=2))

    elif "--test" in sys.argv:
        # Self-test with known-good and known-bad rules
        print("=== axle_integration self-test ===\n")

        good = RuleCandidate(
            name="iterateOne",
            classification="equivalence",
            lhs_template=".iterate 1 (.var 0)",
            rhs_template=".var 0",
            source="test",
        )
        bad = RuleCandidate(
            name="badRule",
            classification="equivalence",
            lhs_template=".sbox 7 (.var 0)",
            rhs_template=".sbox 5 (.var 0)",
            source="test",
        )

        # Round-trip checks
        assert round_trip_check(good), "Round-trip failed for good rule"
        assert round_trip_check(bad), "Round-trip failed for bad rule"
        print("Round-trip checks: PASS")

        # Source generation check
        src = generate_lean_source(good)
        assert "verified_iterateOne" in src, "Generated source should contain rule name"
        assert "import SuperHash.Discovery.RuleVerifier" in src, "Should import RuleVerifier"
        assert "verifyCandidate" in src, "Should call verifyCandidate"
        print("Source generation: PASS")

        # Verify: this actually calls lake env lean (slow but thorough)
        if "--full" in sys.argv:
            print("\nFull verification (requires lake):")
            report_good = verify_rule(good, project_path)
            print(f"  iterateOne: {report_good.result.value} ({report_good.elapsed_ms}ms)")

            report_bad = verify_rule(bad, project_path)
            print(f"  badRule: {report_bad.result.value} ({report_bad.elapsed_ms}ms)")

            if report_good.result == VerificationResult.SOUND:
                print("  Good rule verified as SOUND: PASS")
            else:
                print(f"  Good rule verification: {report_good.result.value} "
                      f"(error: {report_good.error_message})")

            if report_bad.result == VerificationResult.UNSOUND:
                print("  Bad rule rejected as UNSOUND: PASS")
            else:
                print(f"  Bad rule verification: {report_bad.result.value}")
        else:
            print("\n(Skipping lake compilation; use --test --full for full verification)")

        print("\nSelf-test: PASS")


if __name__ == "__main__":
    main()
